name = "google-hub"
compatibility_date = "2026-05-03"

# Supports `wrangler pages deploy dist` workflows.
pages_build_output_dir = "dist"

# Supports `wrangler deploy` workflows by uploading built static assets.
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
